import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar"
import Header from "../components/Header"
import { ThemeProvider } from "@/components/theme-provider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "NeuroLife",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressContentEditableWarning>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider 
         attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange>
         <SidebarProvider>
      <AppSidebar />
      <div className="flex min-h-screen w-full flex-col">
      <Header/>
      <main className="flex flex-1 flex-col px-4 pt-10 xl:px-8">
        {children}
      </main>
      </div>
    </SidebarProvider>
    </ThemeProvider>
      </body>
    </html>
  );
}
